---
# defaults file for falcon_configure

# Whether to enable or disable the logging of sensitive data being exposed in API calls.
# By default, this is enabled.
#
# Disabling this can expose your API credentials and authorization token.
#
falcon_api_enable_no_log: yes

# Controls whether you would like to set or delete options associated with the Falcon Sensor.
# The default is `yes` - to SET options.
falcon_option_set: yes

# CrowdStrike API URL for downloading the Falcon sensor. Possible values:
#       us-1:       api.crowdstrike.com
#       us-2:       api.us-2.crowdstrike.com
#       eu-1:       api.eu-1.crowdstrike.com
#       us-gov-1:   api.laggar.gcw.crowdstrike.com
#
falcon_cloud: "api.crowdstrike.com"

# Auto-discover the CrowdStrike Cloud API Region. When disabled,
# 'falcon_cloud' should be changed to the appropriate cloud region.
#
falcon_cloud_autodiscover: true

# Your Falcon Customer ID (CID) used to associate your sensor.
#
falcon_cid:

# 'Client ID' and 'Client Secret' for authentication against the CrowdStrike
# API. If unknown, get it from the CrowdStrike support portal:
#
#   https://falcon.crowdstrike.com/support/api-clients-and-keys
#
falcon_client_id:
falcon_client_secret:

# Installation tokens prevent unauthorized hosts from being accidentally or maliciously added
# to your Customer ID (CID). Installation tokens are an optional security
# measure for your CID. For more details:
# https://falcon.crowdstrike.com/support/documentation/20/falcon-sensor-for-linux#optional:-installing-to-a-cid-that-requires-installation-tokens
#
falcon_provisioning_token:

# Falcon requires that a master image remove the Falcon Agent ID (AID). This
# ensures instances spun up from the master receive their own, unique,
# Falcon Agent ID.
#
# If installing this role on a base AMI or master image, set this flag
# to 'true|yes'.
#
falcon_remove_aid:

######### PROXY CONFIG #########
# Whether to enable or disable the Falcon sensor to use a proxy. Set this value to either
# 'true|yes' or 'false|no'.
#
# NOTE: To enable the proxy - use `false|no`
#
falcon_apd:

# The Falcon Proxy host. Can be either the FQDN or IP.
#
falcon_aph:

# Falcon Proxy port associated with the proxy host.
#
falcon_app:
################################

# Configure additional traces for debugging. Options are:
# [none|err|warn|info|debug]
#
falcon_trace:

# Falcon allows the configuration of additional features to the sensor. Valid values are:
# [none,[enableLog[,disableLogBuffer]]] and are passed in as
# a list.
#
# Example
#   falcon_feature:
#     - enableLog
#     - disableLogBuffer
#
falcon_feature:

# Whether to enable or disable the ability to log messages to disk. Set this value to either
# 'true|yes' or 'false|no'.
#
falcon_message_log:

# Configure Falcon sensor with Pay-As-You-Go billing. Useful for cloud environments.
# Valid values are: [default|metered]
#
falcon_billing:

# Sensor grouping tags are optional, user-defined identifiers you can use to group and filter hosts.
# If using tags, ensure the following requirements are met:
#   * Tags can include these characters: a-zA-Z0-9-_/
#   * Tags can't include these characters: spaces and commas
#   * To assign multiple tags, separate tags with commas.
#   * The combined length of all tags for a host, including comma separators, cannot exceed 256 characters.
#
# Example
#   falcon_tags: 'Washington/DC_USA,Production'
falcon_tags:

# Configure the Falcon sensor to use a specific backend.
# Valid values are: [auto|bpf|kernel]
#
# This is only available for Linux systems on sensors greater than 6.47.0.
#
falcon_backend:

# Ansible become method for Windows systems.
# The default is runas
#
falcon_windows_become_method: runas

# Ansible become user for Windows systems.
# The default is SYSTEM
#
falcon_windows_become_user: SYSTEM
