---
minor_changes:
  - falcon_configure role - Add support for CsSensorSettings utility on Windows sensor 6.42+ to configure grouping tags post-installation (https://github.com/CrowdStrike/ansible_collection_falcon/issues/304)
