---
# defaults file for falcon_install

# Whether to enable or disable the logging of sensitive data being exposed in API calls.
# By default, this is enabled.
#
# Disabling this can expose your API credentials and authorization token.
#
falcon_api_enable_no_log: yes

# Whether or not to enable run_once for API calls.
# By default, this is enabled.
#
falcon_api_auth_run_once: yes

# Whether or not to ignore errors associated with unsupported Falcon Sensor Kernel
# configurations.
#
# By default, this is disabled - which will fail the play when the Falcon Sensor and Kernel
# are unsupported.
#
falcon_skip_kernel_compat_check: no

# This installer is capable of three different installation
# methods:
#
#   api:         Default: Fetch the latest installer directly from the CrowdStrike API.
#   url:         Fetch installer from a URL
#   repo:        Install from a package repository like APT, DNF, or YUM
#   file:        Install from a local file
#
falcon_install_method: api

# If the installation method is 'file', provide the absolute path to the installer file.
#
falcon_localfile_path:

# If the installation method is 'file', specify whether to remove the local file after installation.
# By default, this is disabled in the event the falcon_localfile_path is set to a shared file
# system location.
#
falcon_localfile_cleanup: no

# Specify whether or not to verify the Falcon sensor Linux based packages.
# By default, this is enabled - which will handle the installation and importing
# of the CrowdStrike Falcon sensor GPG Key.
#
falcon_gpg_key_check: yes

# CrowdStrike API URL for downloading the Falcon sensor. Possible values:
#       us-1:       api.crowdstrike.com
#       us-2:       api.us-2.crowdstrike.com
#       eu-1:       api.eu-1.crowdstrike.com
#       us-gov-1:   api.laggar.gcw.crowdstrike.com
#
falcon_cloud: "api.crowdstrike.com"

# Auto-discover the CrowdStrike Cloud API Region. When disabled,
# 'falcon_cloud' should be changed to the appropriate cloud region.
#
falcon_cloud_autodiscover: true

# Your Falcon Customer ID (CID) used to associate your sensor.
#
# Note: This variable for the falcon_install role only affects and
#       applies to Windows installations.
#
falcon_cid:

# 'Client ID' and 'Client Secret' for authentication against the CrowdStrike
# API. If unknown, download from the CrowdStrike support portal:
#
#   https://falcon.crowdstrike.com/support/api-clients-and-keys
#
falcon_client_id: ""
falcon_client_secret: ""

# The Falcon sensor version to install. This allows you to pin a specific sensor
# version.
#
# NOTE: This variable will be overriden by falcon_sensor_update_policy_name.
#
falcon_sensor_version: ""

# The Falcon sensor version to install by N-X. By default, this is the latest sensor version.
# Setting the value to 1 would install the sensor at N-1.
# The value must be an integer between 0 and 5 inclusive.
#
# NOTE: This variable will be overriden by falcon_sensor_update_policy_name or falcon_sensor_version.
#
falcon_sensor_version_decrement: 0

# The name of the Falcon Sensor Update Policy to use in order to specify the Falcon sensor
# version to install. This is optional, however, if specified, please note that this will
# override the falcon_sensor_version_decrement and falcon_sensor_version variables.
#
# Note: To use the default Falcon Sensor update policy:
#   falcon_sensor_update_policy_name: "platform_default"
#
falcon_sensor_update_policy_name: ""

# Whether or not to enable run_once for the Sensor update policy API calls.
# By default, this is enabled.
#
falcon_sensor_update_policy_run_once: yes

# Where should the sensor file be downloaded to on Linux and MacOS systems?
# By default, this will be the temp OS filesystem
#
falcon_install_tmp_dir: "/tmp"

# If the installation method is 'url', provide the url for the sensor to
# be downloaded from.
#
falcon_download_url:

# If 'url' is authenticated, provide credentials.
falcon_download_url_username:
falcon_download_url_password:

# If using 'api' or 'url' methods, the number of retries the
# installer should attempt.
#
falcon_retries: 3

# If using 'api' or 'url' methods, the time (in seconds) the installer
# should wait between retries.
#
falcon_delay: 3

# Number of times to retry sensor install on windows
#
falcon_windows_install_retries: 10

# Number of seconds to wait to retry sensor install
# on windows in the event of a failure
#
falcon_windows_install_delay: 120

# Where should the sensor file be downloaded to on Windows systems?
# By default, this will be the temp OS filesystem
#
# For Windows, this can be "%SYSTEMROOT%\\Temp"
#
falcon_windows_tmp_dir: "%SYSTEMROOT%\\Temp"

# Additional install arguments beyond the default required
#
# Note: /quiet /install CID={{ falcon_cid }} are already added so do not
#       re-add them here.
#
falcon_windows_install_args: "/norestart"

# Additional arugments to uninstall the sensor.
# You can add your maintenance token here by adding MAINTENANCE_TOKEN=<token>
#
falcon_windows_uninstall_args: "/norestart"

# Ansible become method for Windows systems.
# The default is runas
#
falcon_windows_become_method: runas

# Ansible become user for Windows systems.
# The default is SYSTEM
#
falcon_windows_become_user: SYSTEM
