name: Ansible Test

on:
  push:
    paths:
      - 'plugins/**'
      - '.github/workflows/ansible-test.yml'

  pull_request_target:
    paths:
      - 'plugins/**'
      - '.github/workflows/ansible-test.yml'

jobs:
  ansible-test:
    runs-on: ubuntu-18.04
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }}
      FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y libyaml-dev python3-venv
          python -m pip install --upgrade pip
          pip install ansible yamllint jinja2 pylint pyyaml voluptuous
          curl -L https://raw.githubusercontent.com/crowdstrike/falcon-linux-install-bash/main/falcon-linux-deploy.sh | sudo -E bash

      - name: Build/Install the Collection
        run: |
          collection_file=$( basename $(ansible-galaxy collection build -f | awk -F" " '{print $NF}'))
          ansible-galaxy collection install $collection_file

      - name: Run ansible tests
        run: >-
          cd $HOME/.ansible/collections/ansible_collections/crowdstrike/falcon/ &&
          ansible --version &&
          ansible-test sanity
